# Generated by Django 3.0.8 on 2020-07-24 02:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('calories', models.PositiveSmallIntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='upload', blank=True)),
                ('from_hour', models.TimeField(default=datetime.time(0, 0))),
                ('to_hour', models.TimeField(default=datetime.time(0, 0))),
                ('address', models.CharField(max_length=100)),
                ('average_price', models.PositiveSmallIntegerField(default=0)),
                ('longitude_deg', models.CharField(blank=True, max_length=30)),
                ('latitude_deg', models.CharField(blank=True, max_length=30)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заведение',
                'verbose_name_plural': 'Заведения',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('photo', models.ImageField(upload_to='upload/dish', blank=True)),
                ('total_calories', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('price', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ingredients', models.ManyToManyField(to='places.Ingredient')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Place')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
            },
        ),
    ]
