# Generated by Django 3.0.4 on 2020-07-23 04:15
import csv

from django.db import migrations
from apps.places import parser
from apps.places.models import Ingredient


def add_ingredients(apps, schema_editor):
    queryset = Ingredient.objects.all()
    if not queryset.count():
        parser.main()
    with open('./media/ingredients.csv', 'r') as file:
        reader = csv.reader(file)
        lst = list(reader)
        for row in lst:
            Ingredient.objects.get_or_create(name=row[0], calories=row[1])


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_ingredients),
    ]
